export const CATEGORY_SEEDS = [
  { slug: "artificial-intelligence", name: "Artificial Intelligence", sortOrder: 10, description: "Models, agents, research, and applied AI systems." },
  { slug: "software-development", name: "Software Development", sortOrder: 20, description: "Languages, frameworks, tooling, and engineering practice." },
  { slug: "cloud-computing", name: "Cloud Computing", sortOrder: 30, description: "Hyperscalers, platforms, and cloud-native infrastructure." },
  { slug: "cybersecurity", name: "Cybersecurity", sortOrder: 40, description: "Threats, defenses, identity, and security engineering." },
  { slug: "data-engineering", name: "Data Engineering", sortOrder: 50, description: "Pipelines, warehouses, lakes, and analytics platforms." },
  { slug: "devops", name: "DevOps", sortOrder: 60, description: "CI/CD, platform engineering, SRE, and operations." },
  { slug: "open-source", name: "Open Source", sortOrder: 70, description: "Foundations, projects, and community releases." },
  { slug: "startups-funding", name: "Startups & Funding", sortOrder: 80, description: "New companies, rounds, and ecosystem news." },
  { slug: "big-tech", name: "Big Tech", sortOrder: 90, description: "Product launches and strategy from large vendors." },
  { slug: "consumer-technology", name: "Consumer Technology", sortOrder: 100, description: "Devices, gadgets, and consumer platforms." },
  { slug: "networking", name: "Networking", sortOrder: 110, description: "Internet infrastructure, protocols, and connectivity." },
  { slug: "telecommunications", name: "Telecommunications", sortOrder: 120, description: "Mobile, 5G/6G, and carrier technology." },
  { slug: "quantum-computing", name: "Quantum Computing", sortOrder: 130, description: "Quantum hardware, algorithms, and research." },
  { slug: "robotics", name: "Robotics", sortOrder: 140, description: "Autonomous systems, industrial and humanoid robots." },
  { slug: "ar-vr", name: "AR/VR", sortOrder: 150, description: "Spatial computing, headsets, and mixed reality." },
  { slug: "biotechnology", name: "Biotechnology", sortOrder: 160, description: "Computational biology and tech-enabled life sciences." },
  { slug: "government-technology", name: "Government Technology", sortOrder: 170, description: "Public-sector digital policy and standards." },
  { slug: "research-innovation", name: "Research & Innovation", sortOrder: 180, description: "Labs, papers, and long-horizon technology." },
  { slug: "conferences-events", name: "Conferences & Events", sortOrder: 190, description: "Developer conferences, summits, and industry shows." },
] as const;
